# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.username="ubuntu"
  config.ssh.password="ubuntu"
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  config.vm.define :SubutaiMGMT9 do |conf|
    conf.vm.box="sn"
    conf.vm.provider "virtualbox" do |v|
      v.name="SubutaiMGMT9"
    end
  end


  config.vm.define :SubutaiRH19 do |conf|
    conf.vm.box="sn"
    conf.vm.provider "virtualbox" do |v|
      v.name="SubutaiRH19"
    end
  end

end
