# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.username="ubuntu"
  config.ssh.password="ubuntu"
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true


  config.vm.define :SubutaiMGMT4 do |conf|
    conf.vm.box="sn"
    conf.vm.provider "virtualbox" do |v|
      v.name="SubutaiMGMT4"
      v.customize ["modifyvm", :id, "--macaddress1", "08002770BDBB" ]
    end
  end

end
